#!/bin/sh

set -eu

REPO_ROOT="$(git rev-parse --show-toplevel)"
GRUMPHP_DOCKER="$REPO_ROOT/scripts/grumphp-docker.sh"
CONTAINER_GIT_DIR="/var/www/project"
GIT_USER="$(git config user.name)"
GIT_EMAIL="$(git config user.email)"
COMMIT_MSG_FILE="$1"

case "$COMMIT_MSG_FILE" in
    /*) ;;
    *) COMMIT_MSG_FILE="$REPO_ROOT/$COMMIT_MSG_FILE" ;;
esac

CONTAINER_COMMIT_MSG_FILE="${CONTAINER_GIT_DIR}${COMMIT_MSG_FILE#$REPO_ROOT}"

DIFF="$(git -c diff.mnemonicprefix=false -c diff.noprefix=false --no-pager diff --raw -r -p -m -M --full-index --no-color --staged | cat)"

printf "%s\n" "$DIFF" | "$GRUMPHP_DOCKER" backend/vendor/bin/grumphp git:commit-msg "--git-user=$GIT_USER" "--git-email=$GIT_EMAIL" "$CONTAINER_COMMIT_MSG_FILE"
