#!/bin/sh

set -eu

REPO_ROOT="$(git rev-parse --show-toplevel)"
GRUMPHP_DOCKER="$REPO_ROOT/scripts/grumphp-docker.sh"

DIFF="$(git -c diff.mnemonicprefix=false -c diff.noprefix=false --no-pager diff --raw -r -p -m -M --full-index --no-color --staged | cat)"

printf "%s\n" "$DIFF" | "$GRUMPHP_DOCKER" backend/vendor/bin/grumphp git:pre-commit --skip-success-output
